version: '3'
services:
  mysql:
    container_name: ScheRem-mysql
    build:
      dockerfile: docker/mysql/Dockerfile
      context: .
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app-net

  backend:
    container_name: ScheRem-backend
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    ports:
      - "5001:5001"
    volumes:
      - type: bind
        source: ./
        target: /app
    command: python ./src/main.py
    tty: true
    restart: always
    networks:
      - app-net
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  app-net:
    driver: bridge